TOOLS-2689
mongodb/mongo-tools pull request #325
Opened 2020-10-12 08:27 UTC by tfogo

2020-10-12 18:56 UTC, pmeredit commented on release/aws/aws.go
> +func (a *AWS) UploadBytes(bucket, objPath, filename string, reader io.Reader) error {
Nice refactor

2020-10-12 20:58 UTC, pmeredit requested changes
Just a small request

2020-10-12 20:58 UTC, pmeredit commented on release/download/download.go
> +
We should have doc comments for exported functions.

2020-10-19 18:31 UTC, varsha804 approved these changes
lgtm!

2020-10-19 19:38 UTC, pmeredit approved these changes
LGTM!

2020-10-20 10:36 UTC, merged