TOOLS-2584: Restoring single BSON file should use db set in URI
mongodb/mongo-tools pull request #352
Opened 2021-02-23 18:53 UTC by varsha804

2021-02-23 20:59 UTC, tfogo requested changes
In order to make this work, we have to remove `DB` and `Collection` from the `NSOptions` struct. We would also need to add `Namespace: true` to the `EnabledOptions` struct we pass to `options.New()`. The reason is currently the `NSOptions` are added as a group to the `ToolOptions.parser` but the `ToolOptions.Namespace` struct is not. So `-d` and `-c` do not set any values in `ToolOptions.Namespace` (though the URI database will).

Unfortunately, if we do this we won't get the custom help text for `-d` and `-c` in mongorestore. It would be nice if you could find a way to keep the custom help text too. It might be easier to achieve this by keeping mongorestore using `NSOptions` and do some sort of normalization of the two options. For example adding more logic to where we currently do this in `ParseOptions()`:

```
opts.Namespace = &options.Namespace{DB: nsOpts.DB}
```

2021-02-23 21:19 UTC, varsha804 commented on mongorestore/options.go
> +		options.EnabledOptions{Auth: true, Connection: true, Namespace: true, URI: true})
^

2021-02-23 21:19 UTC, varsha804 commented on mongorestore/options.go
> +	}
^

2021-02-23 21:21 UTC, varsha804 commented
@tfogo Oh, I actually did add `Namespace: true` to `EnabledOptions, and I modified `ParseOptions()` like so:
```
if opts.DB == "" {
		opts.Namespace = &options.Namespace{DB: nsOpts.DB, Collection: nsOpts.Collection}
	}
```
I kept the `DB` and `Collection` fields in `NSOptions` so I could make that change.

Sorry if that wasn't clear; I probably should've pointed out those changes with some comments! Will do so now.

2021-02-23 21:22 UTC, varsha804 commented on mongorestore/options.go
> +	}
^

2021-02-23 21:22 UTC, varsha804 commented on mongorestore/options.go
> +		options.EnabledOptions{Auth: true, Connection: true, Namespace: true, URI: true})
^

2021-03-02 16:45 UTC, tfogo commented
@varsha804, I'm so sorry I totally messed up here. I 100% should have seen those changes - it's absolutely my fault. I think I confused myself when I was looking at my local repo and I thought I had your changes checked out but I did not.

However there's still a problem that we have duplicates of the `--db` and `--collection` options. From the output of `--help`:

```
namespace options:
  -d, --db=<database-name>                                  database to use
  -c, --collection=<collection-name>                        collection to use

uri options:
      --uri=mongodb-uri                                     mongodb uri connection string

namespace options:
  -d, --db=<database-name>                                  database to use when restoring from a BSON file
  -c, --collection=<collection-name>                        collection to use when restoring from a BSON file
      --excludeCollection=<collection-name>                 DEPRECATED; collection to skip over during restore (may be specified multiple times to exclude additional collections)
      --excludeCollectionsWithPrefix=<collection-prefix>    DEPRECATED; collections to skip over during restore that have the given prefix (may be specified multiple times to exclude additional prefixes)
      --nsExclude=<namespace-pattern>                       exclude matching namespaces
      --nsInclude=<namespace-pattern>                       include matching namespaces
      --nsFrom=<namespace-pattern>                          rename matching namespaces, must have matching nsTo
      --nsTo=<namespace-pattern>                            rename matched namespaces, must have matching nsFrom
```

And I'm not entirely sure how the `--db` and `--collection` options will get parsed into the data structures. I think the simplest solution here is to remove `DB` and `Collection` from the `NSOptions` struct. That will mean we'll lose the custom help text for `--db` and `--collection` for mongorestore. Could you also open a ticket in the CLI options rationalization epic about adding those custom help descriptions back in? I expect we'll need to restructure the options logic to make it possible.

2021-03-02 16:46 UTC, tfogo requested changes
(see comment above)

2021-03-02 17:49 UTC, varsha804 commented
@tfogo Oh, no worries! Easy mistake to make 😊

2021-03-03 14:38 UTC, tfogo approved these changes
LGTM!

2021-03-03 15:12 UTC, merged