TOOLS-2721: Add RHEL8 ARM to Tools
mongodb/mongo-tools pull request #366
Opened 2021-04-21 18:17 UTC by huan-Mongo

2021-04-22 09:53 UTC, mastertheknife commented on release/platform/platform.go
> +		Arch:      "arm64",
I think arch should be "aarch64". In RHEL world its called "aarch64", but in Debian\Ubuntu its indeed "arm64"

2021-04-22 09:54 UTC, mastertheknife commented on release/platform/platform.go
> +		Arch:      "arm64",
```
root@removed:~ $ rpm --eval '%{_arch}'
aarch64
```

2021-04-22 17:14 UTC, rychipman requested changes
I think we also need to add `rhel82` entries to `repo-config.yaml`

2021-04-22 17:14 UTC, rychipman commented on release/platform/platform.go
> +		Arch:      "arm64",
a couple suggestions:
- let's add a `RPMArch()` method similar to `DebianArch()`
- let's create constants for these architecture strings, similar to what we've done for OS, Pkg, and Repo

2021-04-26 19:40 UTC, huan-Mongo commented
I have added `rhel82` entries to `repo-config.yaml`, the `RPMArch()` function, as well as the architecture constant.

2021-04-26 21:00 UTC, rychipman requested changes

2021-04-26 21:07 UTC, huan-Mongo commented on release/release.go
> +		vStr, p.RPMArch(),
I see. The substitution is added.

2021-04-26 21:07 UTC, huan-Mongo commented on release/platform/platform.go
> +		Arch:      ArchArm64,
Done. This has been regrouped.

2021-04-26 21:11 UTC, huan-Mongo commented on etc/repo-config.yml
> +  - name: rhel82
Done!

2021-04-28 01:40 UTC, rychipman approved these changes
one typo in the repo config, but otherwise LGTM

2021-04-28 01:40 UTC, rychipman commented on etc/repo-config.yml
> +    bucket: repo.mongodb.org
```suggestion
    bucket: repo.mongodb.com
```

2021-04-29 13:59 UTC, merged