TOOLS-3185 Replace hard-coded transaction oplog data with code to generate that data
mongodb/mongo-tools pull request #474
Opened 2022-10-04 21:53 UTC by autarch

2022-10-04 21:56 UTC, autarch commented
Note for reviewers: The `mongorestore_txn_test.go` file has been essentially replaced. It's probably easier to look at the file as a whole than to look at the diff.

2022-10-05 17:15 UTC, tfogo requested changes
The overall approach here seems like we're not fully achieving what we want. We're generating transactions but then manipulating the oplog entries directly to change the `lsid`, `txnNumber`, `prevOpTime`, `partialTxn`, and `prepare` fields. This feels like a hybrid of having generated and hard-coded test cases. 

I think we should try to try to fully generate our test cases. I think that would be cleaner and more robust.

2022-10-05 18:01 UTC, autarch commented on mongorestore/mongorestore_txn_test.go
> +	_, err = session.WithTransaction(ctx, func(sessCtx mongo.SessionContext) (interface{}, error) {
I don't know why I didn't do it this way, to be honest. I think I got lost a bit in the weeds.

2022-10-05 18:02 UTC, autarch commented
> The overall approach here seems like we're not fully achieving what we want. We're generating transactions but then manipulating the oplog entries directly to change the `lsid`, `txnNumber`, `prevOpTime`, `partialTxn`, and `prepare` fields. This feels like a hybrid of having generated and hard-coded test cases.
> 
> I think we should try to try to fully generate our test cases. I think that would be cleaner and more robust.

I don't think we can _fully_ generate them. At the very least, AFAICT there is no easy way to generate partial transaction, prepared transaction, commits, and aborts. I did experiment with larger document sizes, but that didn't seem to do the trick.

2022-10-05 18:05 UTC, autarch commented on mongorestore/mongorestore_txn_test.go
> +	_, err = session.WithTransaction(ctx, func(sessCtx mongo.SessionContext) (interface{}, error) {
Oh, I _do_ remember why I did it this way. There's basically no documentation for the `applyOps` command. This is all I could find - https://www.mongodb.com/docs/manual/reference/command/applyOps/. I think now that I have a first draft of the code I can generate the right `applyOps` command, but when I started all this I had no clue how to do this.

2022-10-05 18:06 UTC, autarch commented on mongorestore/mongorestore_txn_test.go
> +	_, err = session.WithTransaction(ctx, func(sessCtx mongo.SessionContext) (interface{}, error) {
That said, if I _do_ run an `applyOps` command I will have to just hard-code a bunch of raw ops. Is that better than running a transaction and then fiddling with the resulting oplog? I'll give it a try and share the result.

2022-10-05 18:18 UTC, autarch commented on mongorestore/mongorestore_txn_test.go
> +	_, err = session.WithTransaction(ctx, func(sessCtx mongo.SessionContext) (interface{}, error) {
Actually, the more I think about it the more I think this is _not_ the right way to do this. The whole point of my changes was to remove the hard-coded ops in the JSON file. If I have to just generate the equivalent ops in code what's the point? Right now I'm writing this:

```go
	ns := strings.Join([]string{dbName, coll}, ".")
	ops := []db.Oplog{
		{
			Operation: "i",
			Namespace: ns,
			Object: bson.D{
				{"_id", 0},
				{"x", 0},
			},
			Query: bson.D{{"_id", 0}},
		},
		{
			Operation: "u",
			Namespace: ns,
			Object: bson.D{
				{"_id", 0},
				{"x", 1},
			},
			Query: bson.D{{"_id", 0}},
		},
	}

    // This doesn't actually work but that's beside the point for now.
	opsBson, err := bson.Marshal(ops)
	require.NoError(err)

	cmd := bson.M{"applyOps": opsBson}
	res := client.Database(dbName).RunCommand(ctx, cmd)
	require.NoError(res.Err())
```

This isn't that different from what I have in terms of how much knowledge of the ops is hard-coded. The fact that it's moved from the JSON file directly into the code doesn't make much of a difference.

Admittedly, what I ended up with _also_ has the same problem. There's a lot of stuff that's hard-coded in my approach too.

2022-10-05 18:20 UTC, autarch commented
> > The overall approach here seems like we're not fully achieving what we want. We're generating transactions but then manipulating the oplog entries directly to change the `lsid`, `txnNumber`, `prevOpTime`, `partialTxn`, and `prepare` fields. This feels like a hybrid of having generated and hard-coded test cases.
> > I think we should try to try to fully generate our test cases. I think that would be cleaner and more robust.
> 
> I don't think we can _fully_ generate them. At the very least, AFAICT there is no easy way to generate partial transaction, prepared transaction, commits, and aborts. I did experiment with larger document sizes, but that didn't seem to do the trick.

To further elaborate on this. I did try generating these and could not do so with a repl set. I asked in the Server channel and they suggested using sharding. But none of our tests execute against a sharded cluster, and in the sharding case it's not clear where to get the oplogs from. We can't connect to `local` via `mongos`. So which shard do I connect to? Do I have to find the right shard repl set for each operation somehow? It seemed to be getting incredibly complicated.

2022-10-07 21:08 UTC, tfogo commented
Okay, so we can't generate the oplog entries without using a sharded cluster. I think we should probably be testing against a sharded cluster anyway. Especially as we move towards a sharding-first approach as a company. 

But for this ticket, I think we've already spent a lot of time on this. As a quick solution, I would like to just create two `transaction.json` files, one for before 6.1 and one for 6.1+. I think that's the simplest and least time-consuming way forward. But I think it's okay to add 2 tickets: one for adding sharded clusters to the tests, and another to generate these transaction oplogs on a sharded cluster and only run them in the sharded tests.

For this ticket, you need to replace occurrences of this:

```
{"op":"u","ns":"txntest.c","o":{"$set":{"x":1}},"o2":{"_id":0}
```

With this:

```
{"op":"u","ns":"txntest.c","o":{"$v":2,"diff":{"u":{"x":1}}},"o2":{"_id":0}
```

The change comes from [PM-1460](https://jira.mongodb.org/browse/PM-1460). You can read more about the change in the design doc. Support for the $v:1 update format was removed in [SERVER-50301](https://jira.mongodb.org/browse/SERVER-50301) and now we only support the version introduced in [PM-1460](https://jira.mongodb.org/browse/PM-1460).

Does that sound like an okay plan for this ticket?

2022-10-07 21:12 UTC, autarch commented
> Does that sound like an okay plan for this ticket?

Sure, that's fine.

2022-10-14 18:43 UTC, autarch commented
In the test run here - https://spruce.mongodb.com/version/63499388a4cf475873ff00cf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC - we can see the the integration-latest* tests are now passing.

2022-10-17 16:26 UTC, tfogo approved these changes
LGTM!

2022-10-18 20:02 UTC, edobranov approved these changes
The approach LGTM % a couple comments in the code from me below, so I'll approve now to not slow things down.

Also I don't think I see the two TOOLS tickets on Jira re: Tim's comment further up:
>  But I think it's okay to add 2 tickets: one for adding sharded clusters to the tests, and another to generate these transaction oplogs on a sharded cluster and only run them in the sharded tests.

If they're not created, we should create them and link them to TOOLS-3185.

2022-10-19 15:37 UTC, autarch commented on .gitignore
> +
Yes, this file is created by the test code.

2022-10-19 15:43 UTC, autarch commented
> Also I don't think I see the two TOOLS tickets on Jira re: Tim's comment further up:
> 
> > But I think it's okay to add 2 tickets: one for adding sharded clusters to the tests, and another to generate these transaction oplogs on a sharded cluster and only run them in the sharded tests.
> 
> If they're not created, we should create them and link them to [TOOLS-3185](https://jira.mongodb.org/browse/TOOLS-3185).

I just made these:

* https://jira.mongodb.org/browse/TOOLS-3206
* https://jira.mongodb.org/browse/TOOLS-3207

2022-10-19 15:45 UTC, autarch commented
evergreen merge

The old hard-coded data no longer worked with Server 6.1 as the format for
updates has changed.

This PR adds a new file with the new format to be used with Server 6.1+.

In the future, we might want to instead generate this data in the test. That
was the first approach I tried, but it's not possible to generate many
transaction scenarios with the Server API as it stands. Specifically,
generating a set of partial transactions or `abortTransaction` and
`commmitTransaction` ops isn't possible, as these are only created based on
Server internals.

2022-10-19 15:52 UTC, merged