TOOLS-3500 Remove use of `filemd5` command in test code
mongodb/mongo-tools pull request #640
Opened 2024-04-05 14:38 UTC by autarch

This seems to have been related to something the `mongofiles` code _used_ to do quite some time in the past. There are no longer any references to the `filemd5` command anywhere else in the tools codebase.

The `filemd5` command if going to be deprecated and eventually removed from the Server.

2024-04-08 14:53 UTC, huan-Mongo requested changes
I think the `filemd5` command was to validate the result of `mongofiles` command, so we cannot remove it.

2024-04-10 13:17 UTC, autarch commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
I replaced this with some code that downlaods the file and compares the downloaded file's md5 hash to the original's.

2024-04-11 13:27 UTC, huan-Mongo commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
So this line should be removed, right?

2024-04-11 13:27 UTC, huan-Mongo reviewed
.

2024-04-11 14:07 UTC, tfogo commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
Yeah it looks like it should be removed. I'm confused why the tests didn't fail. It looks like res should be undefined.

2024-04-15 14:49 UTC, autarch commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
We don't run any of the "legacy" tests for patches right now. I think that was an oversight from when I moved the GitHub PR aliases to the Evergreen conf and wrote code to generate that list of aliases. I just updated that to include the "legacy" tests.

2024-04-15 15:52 UTC, autarch commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
So when I added the legacy tests back to the GH PR aliases, they did fail. I pushed a fix for this test to remove all references to `res`.

2024-04-16 13:01 UTC, autarch commented on test/legacy42/jstests/tool/gridfs.js
>      assert.eq(numChunks, res.numChunks);
Ok, the tests are now running in CI and they passed.

2024-04-16 15:00 UTC, huan-Mongo approved these changes
LGTM % the lint failure.

2024-04-16 15:34 UTC, autarch commented
> LGTM % the lint failure.

The lint failure is also happening in `master`. It looks like an infra thing:

> [2024/04/15 23:56:42.726] sh: line 5: /opt/node/bin/npm: No such file or directory

https://parsley.mongodb.com/evergreen/mongo_tools_static_lint_js_patch_ac0ae2543783578632e6beefde9914b9cc123eb4_661d4cfa1b2cab000771c4fb_24_04_15_15_51_23/0/task?bookmarks=0,51,74

2024-04-29 17:38 UTC, tfogo approved these changes
LGTM

2024-04-30 03:17 UTC, merged