Add release notes for 100.10.0 and update release process
mongodb/mongo-tools pull request #714
Opened 2024-07-25 14:26 UTC by tdq45gj

2024-07-25 15:14 UTC, autarch requested changes
As I said, I think we should be very clear about what the security fix is for.

2024-07-25 15:14 UTC, autarch commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3615'>TOOLS-3615</a>] -         Security Finding: Update package `crypto`
```suggestion
<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3615'>TOOLS-3615</a>] -         Security Finding: Update package `golang.org/x/crypto` to address [CVE-2022-30636](https://www.cve.org/CVERecord?id=CVE-2022-30636)
```

2024-07-25 18:52 UTC, rohshar commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3546'>TOOLS-3546</a>] -         Support vectored insertion oplog format
Since we're including the epic in should we omit the issues in it? Seems like thats what we did in 100.9.0: https://github.com/mongodb/mongo-tools/blob/master/CHANGELOG.md#10090

2024-07-25 18:58 UTC, tdq45gj commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3546'>TOOLS-3546</a>] -         Support vectored insertion oplog format
We released 100.9.0 without doing the tickets in the epic. I would prefer to keep the tickets in the release log to avoid manually picking them out from the generated content.

2024-07-25 19:13 UTC, autarch requested changes
Looks good % a few small things.

2024-07-25 19:13 UTC, autarch commented on RELEASE.md
> +  bugfix etc.). Make sure all tickets marked at `Mongo Internal` security level should be excluded except from Vulnerability Types.
```suggestion
  bugfix etc.). Make sure that all tickets marked as `Mongo Internal` for their "Security Level" field are excluded from the release notes, _except_ for tickets created for third-party vulnerabilities. These vulnerability tickets will be linked to a corresponding ticket in the internal-only "VULN" Jira project.
```

2024-07-25 19:13 UTC, autarch commented on RELEASE.md
> +  and Tools product manager. Merge once approved.
```suggestion
- Submit a PR with your changes under the release ticket number, request reviews from the TAR Team Leads
  and the DB Tools Product Manager. Merge once approved.
```

2024-07-25 19:13 UTC, autarch commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3574'>TOOLS-3574</a>] -         Run integration tests against 8.0 and add ubuntu2404 variants
This ticket is marked as internal only. But that makes sense. I asked Johnny about this in Slack too.

2024-07-25 19:14 UTC, autarch commented on CHANGELOG.md
> +
```suggestion
This version adds support for MongoDB Server 8.0, and support for Ubuntu 24.04 platforms. It also updates several packages and fixes a bug.

```

2024-07-25 19:14 UTC, autarch commented on CHANGELOG.md
> +
There's an extra newline here.

2024-07-25 20:27 UTC, rohshar approved these changes
lgtm once you resolve dave's comments

2024-07-25 20:27 UTC, rohshar commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3546'>TOOLS-3546</a>] -         Support vectored insertion oplog format
Ok, fine with me

2024-07-25 20:33 UTC, tdq45gj commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3574'>TOOLS-3574</a>] -         Run integration tests against 8.0 and add ubuntu2404 variants
@jddubois Is it okay to remove the "Mongo Internal" label from [TOOLS-3574](https://jira.mongodb.org/browse/TOOLS-3574)?

2024-07-31 13:45 UTC, jddubois approved these changes
LGTM, thanks!

2024-07-31 14:02 UTC, tdq45gj commented on CHANGELOG.md
> +<li>[<a href='https://jira.mongodb.org/browse/TOOLS-3574'>TOOLS-3574</a>] -         Run integration tests against 8.0 and add ubuntu2404 variants
I just removed the internal label from the ticket.

2024-07-31 14:06 UTC, dsahni approved these changes
lgtm, thanks!

2024-07-31 15:30 UTC, autarch approved these changes
LGTM!

2024-07-31 15:52 UTC, merged