TOOLS-3693 Stop using SSH cloning in Evergreen
mongodb/mongo-tools pull request #728
Opened 2024-10-17 18:58 UTC by tdq45gj

This PR adds the evergreen function to generate the token for accessing `10gen/mongo-release` and replaces the usage of ssh cloning with HTTPS.

2024-10-18 14:06 UTC, FGasper requested changes
A couple nits. See what you think.

Thanks!

2024-10-18 14:06 UTC, FGasper commented on release/release.go
> +	}
```suggestion
        const tokenVar := "generated_token_mongo_release"
	token := os.Getenv(tokenVar)
	if token == "" {
		log.Fatalf("The environment must contain a nonempty %#q.", tokenVar)
	}
```

2024-10-18 14:06 UTC, FGasper commented on release/release.go
> +	}
Nit: It’d be nice to make this a separate function here to facilitate easier adaptation to mongosync.

2024-10-18 19:02 UTC, jsflax approved these changes

2024-10-21 17:47 UTC, FGasper approved these changes
LGTM. Thanks!

2024-10-21 17:55 UTC, merged